import { Business, TouristPlace, EcoRoute, CitizenReport, Mission, Reward, TerritorialPassport } from "@/types";

export const MOCK_MUNICIPALITIES = [
  { id: "muni-sab-01", code: "SAB", name: "San Ignacio de Sabaneta", lat: 19.4752, lng: -71.3412 },
  { id: "muni-mon-02", code: "MON", name: "Monción", lat: 19.4167, lng: -71.1680 },
  { id: "muni-vla-03", code: "VLA", name: "Villa Los Almácigos", lat: 19.4110, lng: -71.4415 },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "biz-mon-01",
    province_id: "prov-sr",
    municipality_id: "muni-mon-02",
    category_id: "cat-casabe",
    name: "Fábrica de Casabe Hermanos Rodríguez",
    description: "Auténtico casabe artesanal de Monción, elaborado en burén de barro con yuca agria local.",
    phone: "809-580-2134",
    whatsapp: "829-450-9821",
    lat: 19.4182,
    lng: -71.1665,
    address: "Calle Duarte #45, Monción",
    status: "PUBLISHED",
    is_verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "biz-sab-02",
    province_id: "prov-sr",
    municipality_id: "muni-sab-01",
    category_id: "cat-gastro",
    name: "Café Restaurante El Parque",
    description: "Comida típica sabanetera, carnes al caldero y el mejor café tostado de la sierra.",
    phone: "809-580-1122",
    whatsapp: "809-912-3344",
    lat: 19.4755,
    lng: -71.3410,
    address: "Frente al Parque Juan Rosado, Sabaneta",
    status: "PUBLISHED",
    is_verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "biz-vla-03",
    province_id: "prov-sr",
    municipality_id: "muni-vla-03",
    category_id: "cat-turismo",
    name: "Cabañas Ecoturísticas Río Aminilla",
    description: "Alojamiento ecológico rodeado de pinares y acceso directo a balnearios de montaña.",
    phone: "809-580-8899",
    whatsapp: "829-771-4455",
    lat: 19.4085,
    lng: -71.4420,
    address: "Carretera Los Almácigos - Aminilla Km 3",
    status: "PUBLISHED",
    is_verified: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "biz-mon-04",
    province_id: "prov-sr",
    municipality_id: "muni-mon-02",
    category_id: "cat-gastro",
    name: "Parador & Mirador de la Presa",
    description: "Pescados frescos, chivo liniero y vista panorámica al embalse de la Presa de Monción.",
    phone: "809-580-9900",
    whatsapp: "849-223-1100",
    lat: 19.4290,
    lng: -71.1550,
    address: "Mirador Alto de la Presa, Monción",
    status: "PUBLISHED",
    is_verified: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_TOURIST_PLACES: TouristPlace[] = [
  {
    id: "tour-01",
    municipality_id: "muni-mon-02",
    name: "Presa de Monción y Contraembalse",
    slug: "presa-de-moncion",
    description: "La presa con el muro de tierra más alto del Caribe. Ideal para paseos en bote, pesca deportiva y contemplación de atardeceres.",
    category: "nature",
    lat: 19.4260,
    lng: -71.1580,
    elevation_meters: 390,
    access_difficulty: "EASY",
    is_published: true,
  },
  {
    id: "tour-02",
    municipality_id: "muni-vla-03",
    name: "Balneario El Badén de Aminilla",
    slug: "balneario-el-baden",
    description: "Pozas de aguas cristalinas que bajan de la Cordillera Central entre formaciones rocosas y árboles centenarios.",
    category: "river",
    lat: 19.4050,
    lng: -71.4490,
    elevation_meters: 280,
    access_difficulty: "MODERATE",
    is_published: true,
  },
  {
    id: "tour-03",
    municipality_id: "muni-sab-01",
    name: "Parque Profesor Juan Rosado & Centro Histórico",
    slug: "parque-juan-rosado",
    description: "Epicentro cívico y cultural de San Ignacio de Sabaneta, cargado de historia libertaria y patriotismo.",
    category: "culture",
    lat: 19.4750,
    lng: -71.3415,
    elevation_meters: 140,
    access_difficulty: "EASY",
    is_published: true,
  },
];

export const MOCK_ROUTES: EcoRoute[] = [
  {
    id: "route-01",
    name: "Sendero Ecoturístico de los Pinares de Monción",
    description: "Recorrido entre pinares con vistas panorámicas al valle y llegada a manantiales de montaña.",
    difficulty: "MODERATE",
    distance_km: 6.8,
    estimated_duration_min: 120,
    start_municipality_id: "muni-mon-02",
    elevation_gain_meters: 210,
    is_official: true,
    coordinates: [
      [-71.1680, 19.4167],
      [-71.1640, 19.4210],
      [-71.1590, 19.4250],
      [-71.1550, 19.4290],
    ],
  },
  {
    id: "route-02",
    name: "Ruta del Agua: Balneario Aminilla",
    description: "Caminata accesible bordeando el río Aminilla con pozas naturales para refrescarse.",
    difficulty: "EASY",
    distance_km: 3.2,
    estimated_duration_min: 50,
    start_municipality_id: "muni-vla-03",
    elevation_gain_meters: 80,
    is_official: true,
    coordinates: [
      [-71.4415, 19.4110],
      [-71.4450, 19.4080],
      [-71.4490, 19.4050],
    ],
  },
];

export const MOCK_REPORTS: CitizenReport[] = [
  {
    id: "rep-01",
    province_id: "prov-sr",
    municipality_id: "muni-sab-01",
    category_id: "cat-bache",
    title: "Bache profundo en Calle Próceres de la Restauración",
    description: "Hoyo considerable tras las lluvias de la semana pasada afectando el flujo hacia el hospital.",
    lat: 19.4770,
    lng: -71.3390,
    address_reference: "Cerca de la Farmacia Central",
    status: "IN_PROGRESS",
    priority: "HIGH",
    votes_count: 14,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "rep-02",
    province_id: "prov-sr",
    municipality_id: "muni-mon-02",
    category_id: "cat-alumbrado",
    title: "Falla de luminaria en subida al Mirador",
    description: "Tres postes sin iluminación dejando un tramo oscuro y peligroso para conductores.",
    lat: 19.4240,
    lng: -71.1610,
    address_reference: "Curva antes del Mirador de la Presa",
    status: "RECEIVED",
    priority: "MEDIUM",
    votes_count: 8,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "rep-03",
    province_id: "prov-sr",
    municipality_id: "muni-vla-03",
    category_id: "cat-limpieza",
    title: "Limpieza requerida en acceso a Balneario",
    description: "Desechos acumulados en la entrada del sendero que requieren brigada de recolección.",
    lat: 19.4060,
    lng: -71.4470,
    status: "RESOLVED",
    priority: "LOW",
    votes_count: 22,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    resolved_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const MOCK_MISSIONS: Mission[] = [
  {
    id: "mis-01",
    province_id: "prov-sr",
    municipality_id: "muni-mon-02",
    business_id: "biz-mon-01",
    title: "La Ruta del Casabe Dorado",
    description: "Visita la Fábrica de Casabe Hermanos Rodríguez en Monción y escanea el código en su burén tradicional.",
    mission_type: "SCAN_QR",
    difficulty: "EASY",
    reward_points: 25,
    is_active: true,
    lat: 19.4182,
    lng: -71.1665,
    radius_meters: 100,
    created_at: new Date().toISOString(),
  },
  {
    id: "mis-02",
    province_id: "prov-sr",
    municipality_id: "muni-sab-01",
    tourist_place_id: "tour-03",
    title: "Guardián Histórico de Sabaneta",
    description: "Acude al Parque Profesor Juan Rosado en el corazón de Sabaneta para validar tu presencia territorial.",
    mission_type: "VISIT_LOCATION",
    difficulty: "EASY",
    reward_points: 15,
    is_active: true,
    lat: 19.4750,
    lng: -71.3415,
    radius_meters: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: "mis-03",
    province_id: "prov-sr",
    municipality_id: "muni-vla-03",
    tourist_place_id: "tour-02",
    title: "Explorador de las Aguas Cordilleranas",
    description: "Recorre el sendero hacia el Balneario El Badén de Aminilla y registra tu llegada en Los Almácigos.",
    mission_type: "VISIT_LOCATION",
    difficulty: "MEDIUM",
    reward_points: 40,
    is_active: true,
    lat: 19.4050,
    lng: -71.4490,
    radius_meters: 150,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: "rew-01",
    business_id: "biz-mon-01",
    mission_id: "mis-01",
    business_name: "Fábrica de Casabe Hermanos Rodríguez",
    title: "10% de Descuento en Casabe Gourmet",
    description: "Válido en la compra de paquetes surtidos de casabe con ajo o maní en el local de Monción.",
    reward_type: "DISCOUNT_PERCENTAGE",
    reward_value: 10,
    difficulty_tier: "EASY",
    stock: 8,
    initial_stock: 10,
    is_active: true,
    terms_conditions: "Un cupón por compra. Válido hasta fin de mes.",
  },
  {
    id: "rew-02",
    business_id: "biz-sab-02",
    mission_id: "mis-02",
    business_name: "Café Restaurante El Parque",
    title: "Café Serrano de Cortesía",
    description: "Disfruta un café con leche o espresso serrano con tu almuerzo en Sabaneta.",
    reward_type: "FREE_PRODUCT",
    reward_value: 100,
    difficulty_tier: "EASY",
    stock: 5,
    initial_stock: 15,
    is_active: true,
    terms_conditions: "Presentar código antes de solicitar la cuenta.",
  },
  {
    id: "rew-03",
    business_id: "biz-vla-03",
    mission_id: "mis-03",
    business_name: "Cabañas Ecoturísticas Río Aminilla",
    title: "15% en Estadía Ecoturística",
    description: "Descuento en cabañas familiares de fin de semana en Villa Los Almácigos.",
    reward_type: "DISCOUNT_PERCENTAGE",
    reward_value: 15,
    difficulty_tier: "HARD",
    stock: 3,
    initial_stock: 5,
    is_active: true,
    terms_conditions: "Reserva previa requerida sujeta a disponibilidad.",
  },
];

export const MOCK_PASSPORT: TerritorialPassport = {
  user_id: "user-demo-01",
  display_name: "Rey García",
  reputation: 92,
  stats: {
    places_visited: 7,
    missions_completed: 4,
    rewards_unlocked: 3,
    reports_submitted: 5,
  },
  badges: [
    "PIONERO_TERRITORIAL",
    "EXPLORADOR_DE_SABANETA",
    "IMPULSOR_LOCAL",
    "GUARDIAN_CIVICO",
  ],
};
